-- AlterTable
ALTER TABLE "players" ADD COLUMN     "bank" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "characterId" INTEGER,
ADD COLUMN     "experience" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "faction" TEXT,
ADD COLUMN     "hunger" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "job" TEXT,
ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "money" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "playedTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "premiumPoints" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "thirst" DOUBLE PRECISION NOT NULL DEFAULT 100;
